# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d503d124-3ebc-4ff0-9338-6067ce8d11dc";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-5b4009d8-99b6-4522-a2b6-1bd2b8d6f0f3".device =
    "/dev/disk/by-uuid/5b4009d8-99b6-4522-a2b6-1bd2b8d6f0f3";

  boot.initrd.luks.devices."luks-73f66e02-63e4-47f7-a787-617ca9ac93b6".device =
    "/dev/disk/by-uuid/73f66e02-63e4-47f7-a787-617ca9ac93b6";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0C1E-98D5";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/093bfb3d-a80b-4ad0-8bf9-6d1fa93071d4"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp82s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
